### ISSUE TITLE
What common errors or issues do PHP developers typically encounter when working with object-oriented programming in PHP?

### ISSUE THREAD

**Issue by Leksizz** [Leksizz/test-task#2]

**Comment by theibd56** [comment]
1. Incorrect Use of Visibility Modifiers:

Developers sometimes forget to use the correct visibility modifiers (public, protected, private) for class properties and methods, leading to unexpected access issues.

2. Misunderstanding of Inheritance:

Issues can arise when developers do not fully grasp how inheritance works, such as failing to call the parent constructor using parent::__construct() or incorrectly overriding methods.

3. Not Using Interfaces or Abstract Classes:

Developers may miss the opportunity to use interfaces or abstract classes, leading to less flexible and maintainable code. This can result in tightly coupled classes that are hard to extend or modify.


4. Static vs. Instance Context:

Confusion between static and instance methods/properties can lead to errors, especially when trying to access instance properties from a static context or vice versa.

5. Improper Use of self vs. static:

Using self will refer to the class where the method is defined, while static will refer to the class that is being instantiated. This can cause unexpected behavior in inheritance scenarios.

6. Overusing Static Methods and Properties:

While static methods and properties can be useful, overusing them can lead to procedural code and reduce the benefits of OOP, such as encapsulation and polymorphism.

7. Not Implementing Constructor/Destructor Properly:

Failing to properly implement constructors and destructors can lead to resource leaks or improper initialization of objects.
8. Circular References:

Circular references can lead to memory leaks, especially when using objects that reference each other. PHP's garbage collector may not be able to clean them up properly.
